In [2]:
import numpy as np

X = np.array(
[[73.847017017515, 241.893563180437],
 [68.7819040458903, 162.3104725213],
 [74.1101053917849, 212.7408555565],
 [71.7309784033377, 220.042470303077],
 [69.8817958611153, 206.349800623871],
 [67.2530156878065, 152.212155757083],
 [68.7850812516616, 183.927888604031],
 [68.3485155115879, 167.971110489509],
 [67.018949662883, 175.92944039571],
 [63.4564939783664, 156.399676387112]]
)

In [3]:
X.shape

(10, 2)

In [15]:
def get_mean(matrix):
    i=0
    nums=0
    mean = 0
    while i < len(matrix)-1:
        nums += matrix[i][0]
        mean = nums/len(matrix)
        i+=1
    return mean

In [16]:
test = get_mean(X)
print(test)

62.975736283358216


In [10]:
print(np.mean(X[:, 0]))

69.32138568119487


In [19]:
print(np.mean(X[:, 1]))

187.97774338186304


In [23]:
np.mean(X[:5, 1])

208.667432437037

In [27]:
np.mean(X[8, 0])

67.018949662883

In [28]:
X - np.mean(X, axis=0)

array([[  4.52563134,  53.9158198 ],
       [ -0.53948164, -25.66727086],
       [  4.78871971,  24.76311217],
       [  2.40959272,  32.06472692],
       [  0.56041018,  18.37205724],
       [ -2.06836999, -35.76558762],
       [ -0.53630443,  -4.04985478],
       [ -0.97287017, -20.00663289],
       [ -2.30243602, -12.04830299],
       [ -5.8648917 , -31.57806699]])

In [30]:
np.mean(X, axis=1)

array([157.8702901 , 115.54618828, 143.42548047, 145.88672435,
       138.11579824, 109.73258572, 126.35648493, 118.159813  ,
       121.47419503, 109.92808518])

In [31]:
A = np.array([[1,2], [3,4]])
print( A)

[[1 2]
 [3 4]]


In [32]:
print(np.sum(A))

10


In [33]:
print(np.sum(A, axis=0))

[4 6]


In [34]:
A.shape

(2, 2)